   <table valign="top" border="0" cellpadding="3" cellspacing="0" width="100%">
    <tr>
      <td>
        <div class="cornerBox">
          <div class="content">
            <div style="padding:25px;text-align:left">
              <div align="right"><img src="/pics/logo_70x29px.gif" border="0" alt="AXIS" /></div>
              <p>
                <label class="topTitle">AXIS Soundtrack Your Brand Player</label>
                <br /><br />
                Version: 1.0.0<br /><br />
                Copyright (C) 1995-<script language="javascript" type="text/javascript"> document.write( ( new Date()).getFullYear() );</script>, Axis Communications AB<br />
              </p>
            </div>
          </div>
          <div class="footerLeft"><div class="footerRight"></div></div>
        </div>
      </td>
    </tr>
  </table>
